dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Combustion Inc. Android Example"

include ':app'
include ':combustion-android-ble'
project(':combustion-android-ble').projectDir = new File('combustion-android-ble/combustion-android-ble')